name: faux-crucible-ci

on:
  pull_request:
    branches: [ main ]
    paths:
    - LICENSE
    - '**.md'
    - '.github/rulesets/**'
    - .github/workflows/run-crucible-tracking.yaml
    - .github/workflows/crucible-merged.yaml
    - .github/workflows/faux-crucible-ci.yaml
    - .github/workflows/faux-unittest.yaml
    - 'docs/**'

jobs:
  call-core-crucible-ci:
    uses: perftool-incubator/crucible-ci/.github/workflows/faux-core-crucible-ci.yaml@main
